# Generated by Django 3.2.7 on 2021-10-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perrito',
            options={'verbose_name': 'Perrito', 'verbose_name_plural': 'Perritos'},
        ),
        migrations.AlterModelOptions(
            name='tamaño',
            options={'verbose_name': 'Tamaño', 'verbose_name_plural': 'Tamaños'},
        ),
        migrations.RenameField(
            model_name='tamaño',
            old_name='tamaño',
            new_name='tamaños',
        ),
        migrations.RemoveField(
            model_name='tamaño',
            name='created',
        ),
        migrations.AddField(
            model_name='perrito',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
