# Generated by Django 3.2.7 on 2021-10-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0002_auto_20211003_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='media/mascota_imagenes'),
        ),
    ]
