# Generated by Django 3.2.5 on 2021-10-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0003_alter_perrito_imagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrito',
            name='imagenes',
        ),
        migrations.CreateModel(
            name='PerritoImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/mascota_imagenes')),
                ('perrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascota.perrito')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
