# Generated by Django 3.2.7 on 2021-10-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0004_auto_20211008_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perritoimagenes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
