# Generated by Django 3.2.7 on 2021-10-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0005_alter_perritoimagenes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perritoimagenes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perritos'),
        ),
    ]
