# Generated by Django 3.2.7 on 2021-10-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0006_alter_perritoimagenes_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrito',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portada'),
        ),
    ]
